Account update leaf 4559 - Test Scenario #1
department-of-veterans-affairs/LEAF-Automated-Tests pull request #15
Opened 2024-11-15 19:39 UTC by 22MGreen

This is the end2end test to Verify when a user account is disabled and the previous groups and positions are moved to the new account.  This first scenario accounts for when there are not any groups or positions. I am verifying that the process runs smoothly and there are not any groups or positions that are listed and there are not any errors when running this scenario.  Please only review acctUpdate file.

2024-11-22 18:25 UTC, shaneodd requested changes
I am not able to get this to work properly the branch this test is testing is on the master branch so I am not sure if there is something else with the code or something with the test. 
``` error
Error: Timed out 5000ms waiting for expect(locator).toContainText(expected)

Locator: locator('#grid_groups_info')
- Expected string  -  1
+ Received string  + 15

- No groups found
+
+        Export
+     
+     
+     
+     
+       Group NameCurrent UsernameSelect All Groups
+                                 
+                             
+       Aluminum BooksKozey, Kirstinvtriujtalisha (nexus)Select
+                                         
+                                     
+       
+     
+     
Call log:
  - expect.toContainText with timeout 5000ms
  - waiting for locator('#grid_groups_info')
  -   locator resolved to <div class="grid_table" id="grid_groups_info"></div>
  -   unexpected value ""
  -   locator resolved to <div class="grid_table" id="grid_groups_info"></div>
  -   unexpected value ""
  -   locator resolved to <div class="grid_table" id="grid_groups_info">…</div>
  -   unexpected value "
       Export
    
    
    
    
      Group NameCurrent UsernameSelect All Groups
                                
                            
      Aluminum BooksKozey, Kirstinvtriujtalisha (nexus)Select
                                        
                                    
      
    
    "
  -   locator resolved to <div class="grid_table" id="grid_groups_info">…</div>
  -   unexpected value "
       Export
    
    
    
    
      Group NameCurrent UsernameSelect All Groups
                                
                            
      Aluminum BooksKozey, Kirstinvtriujtalisha (nexus)Select
                                        
                                    
      
    
    "
  -   locator resolved to <div class="grid_table" id="grid_groups_info">…</div>
  -   unexpected value "
       Export
    
    
    
    
      Group NameCurrent UsernameSelect All Groups
                                
                            
      Aluminum BooksKozey, Kirstinvtriujtalisha (nexus)Select
                                        
                                    
      
    
    "
  -   locator resolved to <div class="grid_table" id="grid_groups_info">…</div>
  -   unexpected value "
       Export
    
    
    
    
      Group NameCurrent UsernameSelect All Groups
                                
                            
      Aluminum BooksKozey, Kirstinvtriujtalisha (nexus)Select
                                        
                                    
      
    
    "
  -   locator resolved to <div class="grid_table" id="grid_groups_info">…</div>
  -   unexpected value "
       Export
    
    
    
    
      Group NameCurrent UsernameSelect All Groups
                                
                            
      Aluminum BooksKozey, Kirstinvtriujtalisha (nexus)Select
                                        
                                    
      
    
    "
  -   locator resolved to <div class="grid_table" id="grid_groups_info">…</div>
  -   unexpected value "
       Export
    
    
    
    
      Group NameCurrent UsernameSelect All Groups
                                
                            
      Aluminum BooksKozey, Kirstinvtriujtalisha (nexus)Select
                                        
                                    
      
    
    "
  -   locator resolved to <div class="grid_table" id="grid_groups_info">…</div>
  -   unexpected value "
       Export
    
    
    
    
      Group NameCurrent UsernameSelect All Groups
                                
                            
      Aluminum BooksKozey, Kirstinvtriujtalisha (nexus)Select
                                        
                                    
      
    
    "


  64 |   //Veirfy Goups and Positions is empty have value
  65 |
> 66 |   await expect (page1.locator('#grid_groups_info')).toContainText('No groups found');
     |                                                     ^
  67 |
  68 |  await expect (page1.locator('#grid_positions_info')).toContainText('No Positions found');
  69 |  

    at /usr/app/leaf/tests/acctUpdateMultiple.spec.ts:66:53
```

2024-12-31 15:51 UTC, shaneodd requested changes
This test is also not testing the account updater properly. 

It should follow these steps, keep in mind there are sync services and such that will be required before running the tests.

1. Setup migration of user, make sure the groups we are testing are shown
2. Do the migration
3. Come back to this page and verify things are migrated and the groups  are no longer being migrated over.

2025-01-03 23:14 UTC, 22MGreen commented
Scenario One - Verifies where there is not any groups or positions
Scenario Two - Verifies when there are groups and positions (Having issues with this one in that it fails in different areas)

2025-01-08 21:46 UTC, shaneodd approved these changes

2025-01-09 14:31 UTC, Pelentan approved these changes

2025-01-09 14:32 UTC, merged